### ISSUE TITLE
Minor documentation issue (installing ack on Linux)

### ISSUE THREAD

**Issue by CJBrew** [smolnar/vim-rails-bundle#5]
The Ack package is named ack-grep on Linux; so the apt-get installation line

`sudo apt-get install vim vim-gtk git curl ack ack-grep clang xclip`

should be modified to remove `ack`, which cannot be found.

see http://beyondgrep.com/install/

```
Install a package for your specific OS

ack has been repackaged for most Linux distributions and OS X. On Debian-derived distributions, it is called "ack-grep" because "ack" was already a package for Kanji translation.
```

**Comment by smolnar** [comment]
Fixed by  532b141acbeb7175e0cc9dd3e8af442a79896cb8
