### ISSUE TITLE
Choose from app/models deprecation notes.

### ISSUE THREAD

**Issue by triplepointfive** [smolnar/vim-rails-bundle#6]
Opening models with `F10` (or views etc.) complains for `:R navigation commands are deprecated. Use :E commands instead`
```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  9 2014 17:36:41)
```

**Comment by smolnar** [comment]
Thanks!
Can you make a PR to rename all the :R.... commands to :E....?
