### ISSUE TITLE
Comments highlight

### ISSUE THREAD

**Issue by triplepointfive** [smolnar/vim-rails-bundle#9]
In some file formats like `.vimrc` or git commit message grey background is OK
![screenshot from 2015-07-22 13 07 54](https://cloud.githubusercontent.com/assets/2033821/8823085/d7d52d5a-3072-11e5-9036-6f15fcc8f198.png)
But it's absolutely unreadable when trying to edit comments
![screenshot from 2015-07-22 13 03 45](https://cloud.githubusercontent.com/assets/2033821/8823094/ec4eac52-3072-11e5-91ba-2f3c7fd06026.png)
Not sure where this exactly comes from.

**Comment by smolnar** [comment]
Yeah. What terminal are you using? Could you change selection color of you terminal? I remember, that I had that issue and I think I fixed it by changing selection color in terminal settings to darker one.

**Comment by triplepointfive** [comment]
Thanks, that's worked for me! It's named Intensive Color 1 in konsole.

**Comment by smolnar** [comment]
Glad to hear!
